### PR TITLE
remove dependency on getContainer

### PR DESCRIPTION
**Pull request by gurmukhp**

### CODE REVIEW

**Comment by marmat** [comment]
Side note: [`google.maps.Map`](https://developers.google.com/maps/documentation/javascript/3.21/reference#Map) does seem to offer a `getDiv()` method. I wonder why StreetViewPanorama isn't offering the same. Maybe worth trying to file a feature request...

**Comment by gurmukhp** [comment]
I've reached out to the Maps team regarding the getDiv function, lets see what they say :)

**Comment by gurmukhp** [comment]
Remove event added and docs updated :)

**Comment by marmat** [comment]
LGTM, thanks!

**Pull request merged**
